# Model arguments
model_name_or_path: /gemini/code/merged_model_ckpt861
model_revision: main
torch_dtype: bfloat16
# attn_implementation: flash_attention_2

# Data training arguments
dataset_name: /mnt-nfsdata/MaterialCode/datasets/rl/0723_rl_dataset_8k_clean.parquet 
dataset_prompt_column: 'prompt'
# system_prompt: "You are a materials science expert.\n\nYour response must follow this structure:\n1.  **Reasoning**: Provide your step-by-step reasoning within <think></think> tags.\n2.  **Final Answer**: State your final answer clearly, with the numerical result enclosed in \boxed{}.\n\nThe value inside \boxed{} must follow these rules:\n- **Yield/Tensile Strength**: Number only (unit is implicitly MPa). Example: \boxed{120}\n- **Elongation**: Number followed by the '%' symbol. Example: \boxed{17.0%}\n- **Hardness**: Number only (unit is implicitly HV). Example: \boxed{200}\n- For all other data types, use standard units.\n\nFocus on applying material properties and logical scientific derivation."
# GRPO trainer config
bf16: true
use_vllm: true
do_eval: True
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: /gemini/code/merged_model_ckpt861
hub_strategy: every_save
learning_rate: 2.0e-06
log_completions: True
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 6048
max_steps: -1
num_generations: 8
num_train_epochs: 1
output_dir: /gemini/code/OpenR1/model_ckpt/test_grpo_second
overwrite_output_dir: false
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
push_to_hub: false
report_to:
- tensorboard
reward_funcs:
- material_reward
reward_weights:
- 1.0
save_strategy: "steps"
save_steps: 10
seed: 42
warmup_ratio: 0.1
